Repository openshift/cli-manager, pull requests merged in 2024-08, with the labels that each got.

#92 WRKLDS-1421: Serve metrics server in https
  pkg/cmd/cli-manager/cli_manager.go
  pkg/git/git.go
  pkg/metrics/metrics.go
  test/e2e/bindata/assets/04_deployment.yaml
  test/e2e/bindata/assets/06_service.yaml
  test/e2e/bindata/assets/10_servicemonitor.yaml
Labels: lgtm, approved, jira/valid-reference

#93 WRKLDS-1421: Bump go-containerregistry to 0.20.2
  go.mod
  go.sum
  vendor/github.com/docker/cli/AUTHORS
  vendor/github.com/docker/cli/NOTICE
  vendor/github.com/docker/cli/cli/config/config.go
  vendor/github.com/docker/cli/cli/config/configfile/file.go
  vendor/github.com/docker/cli/cli/config/configfile/file_unix.go
  vendor/github.com/docker/cli/cli/config/credentials/default_store.go
  vendor/github.com/docker/cli/cli/config/credentials/default_store_unsupported.go
  vendor/github.com/docker/cli/cli/config/credentials/file_store.go
  vendor/github.com/docker/cli/cli/config/credentials/native_store.go
  vendor/github.com/docker/docker/AUTHORS
  vendor/github.com/docker/docker/LICENSE
  vendor/github.com/docker/docker/NOTICE
  vendor/github.com/docker/docker/pkg/homedir/homedir_linux.go
  vendor/github.com/docker/docker/pkg/homedir/homedir_others.go
  vendor/github.com/docker/docker/pkg/homedir/homedir_unix.go
  vendor/github.com/docker/docker/pkg/homedir/homedir_windows.go
  vendor/github.com/google/go-containerregistry/pkg/authn/authn.go
  vendor/github.com/google/go-containerregistry/pkg/authn/keychain.go
  vendor/github.com/google/go-containerregistry/pkg/authn/multikeychain.go
  vendor/github.com/google/go-containerregistry/pkg/name/digest.go
  vendor/github.com/google/go-containerregistry/pkg/v1/layout/write.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/fetcher.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/pusher.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/referrers.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/basic.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/bearer.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/write.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#95 WRKLDS-1421: Prepare tekton files specific to release-4.17 branch
  .tekton/cli-manager-4-17-pull-request.yaml
  .tekton/cli-manager-4-17-push.yaml
Labels: lgtm, jira/valid-bug, cherry-pick-approved, backport-risk-assessed, approved, jira/valid-reference

#99 WRKLDS-1421: Add required labels in dockerfile
  Dockerfile
Labels: lgtm, approved, jira/valid-reference

#98 [release-4.17] WRKLDS-1421: Prepare release 4.17
  Dockerfile
  go.mod
  go.sum
  vendor/github.com/docker/cli/AUTHORS
  vendor/github.com/docker/cli/NOTICE
  vendor/github.com/docker/cli/cli/config/config.go
  vendor/github.com/docker/cli/cli/config/configfile/file.go
  vendor/github.com/docker/cli/cli/config/configfile/file_unix.go
  vendor/github.com/docker/cli/cli/config/credentials/default_store.go
  vendor/github.com/docker/cli/cli/config/credentials/default_store_unsupported.go
  vendor/github.com/docker/cli/cli/config/credentials/file_store.go
  vendor/github.com/docker/cli/cli/config/credentials/native_store.go
  vendor/github.com/docker/docker/AUTHORS
  vendor/github.com/docker/docker/LICENSE
  vendor/github.com/docker/docker/NOTICE
  vendor/github.com/docker/docker/pkg/homedir/homedir_linux.go
  vendor/github.com/docker/docker/pkg/homedir/homedir_others.go
  vendor/github.com/docker/docker/pkg/homedir/homedir_unix.go
  vendor/github.com/docker/docker/pkg/homedir/homedir_windows.go
  vendor/github.com/google/go-containerregistry/pkg/authn/authn.go
  vendor/github.com/google/go-containerregistry/pkg/authn/keychain.go
  vendor/github.com/google/go-containerregistry/pkg/authn/multikeychain.go
  vendor/github.com/google/go-containerregistry/pkg/name/digest.go
  vendor/github.com/google/go-containerregistry/pkg/v1/layout/write.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/fetcher.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/pusher.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/referrers.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/basic.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/bearer.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/write.go
  vendor/modules.txt
Labels: lgtm, jira/valid-bug, cherry-pick-approved, backport-risk-assessed, approved, jira/valid-reference

#101 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/cli-manager-pull-request.yaml
  .tekton/cli-manager-push.yaml
Labels: lgtm, ok-to-test, approved

#104 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/cli-manager-4-17-pull-request.yaml
  .tekton/cli-manager-4-17-push.yaml
Labels: lgtm, jira/valid-bug, ok-to-test, cherry-pick-approved, backport-risk-assessed, approved

#107 WRKLDS-1421: Add strictfipsruntime tag in go build
  .tekton/cli-manager-pull-request.yaml
  .tekton/cli-manager-push.yaml
  Makefile
Labels: lgtm, approved, jira/valid-reference

#108 [release-4.17] WRKLDS-1421: Add strictfipsruntime tag in go build
  .tekton/cli-manager-4-17-pull-request.yaml
  .tekton/cli-manager-4-17-push.yaml
  Makefile
Labels: lgtm, jira/valid-bug, cherry-pick-approved, backport-risk-assessed, approved, jira/valid-reference

#113 WRKLDS-1421: Add cluster-monitoring annotation in namespace
  test/e2e/bindata/assets/00_namespace.yaml
Labels: lgtm, approved, jira/valid-reference
